# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcarcenter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='card_date',
            field=models.DateField(blank=True, verbose_name='วันที่ออก'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='card_no',
            field=models.CharField(blank=True, max_length=20, verbose_name='เลขบัตร'),
        ),
    ]
