# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ppcarcenter', '0002_auto_20171129_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='ราคาขาย')),
                ('deposit', models.IntegerField(blank=True, verbose_name='เงินมัดจำ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_purcase_buyer', to='ppcarcenter.Contact', verbose_name='ผู้ซื้อ')),
            ],
            options={
                'verbose_name': 'สัญญาซื้อรถยนต์',
                'verbose_name_plural': 'สัญญาซื้อรถยนต์',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='ราคาขาย')),
                ('deposit', models.IntegerField(blank=True, verbose_name='เงินมัดจำ')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sales_buyer', to='ppcarcenter.Contact', verbose_name='ผู้ซื้อ')),
            ],
            options={
                'verbose_name': 'สัญญาขายรถยนต์',
                'verbose_name_plural': 'สัญญาขายรถยนต์',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='car',
            name='equipments',
            field=models.TextField(blank=True, max_length=100, verbose_name='อุปกรณืติดรถ'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppcarcenter.Car', verbose_name='รถ'),
        ),
        migrations.AddField(
            model_name='sales',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppcarcenter.Car', verbose_name='รถ'),
        ),
        migrations.AddField(
            model_name='sales',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sales_seller', to='ppcarcenter.Contact', verbose_name='ผู้ขาย'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ppcarcenter.Car', verbose_name='รถ'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_purcase_seller', to='ppcarcenter.Contact', verbose_name='ผู้ขาย'),
        ),
    ]
