# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ppcarcenter', '0003_auto_20171130_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='สร้างเมื่อ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='สร้างเมื่อ'),
            preserve_default=False,
        ),
    ]
