# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ppcarcenter', '0004_auto_20171130_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='created_at',
            field=models.DateTimeField(verbose_name='สร้างเมื่อ'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='created_at',
            field=models.DateTimeField(verbose_name='สร้างเมื่อ'),
        ),
    ]
